language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.7']
      env: COMPILER=g++-4.7 CONFIG=Debug

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9 CONFIG=Debug
      
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5.0']
      env: COMPILER=g++-5.0 CONFIG=Debug
      
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5.3']
      env: COMPILER=g++-5.3 CONFIG=Debug
        
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5.3']
      env: COMPILER=g++-5.3 CONFIG=Release
      
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang++-3.3']
      env: COMPILER=clang++-3.3 CONFIG=Debug
      
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang++-3.5']
      env: COMPILER=clang++-3.5 CONFIG=Debug
        
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang++-3.5']
      env: COMPILER=clang++-3.5 CONFIG=Release
      
    - os: osx
      env: COMPILER=clang++ CONFIG=Debug
      
    - os: osx
      env: COMPILER=clang++ CONFIG=Release
      

before_script:
  - export BASEDIR=$PWD
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER `which $COMPILER` -D CMAKE_BUILD_TYPE=$CONFIG -D ENABLE_TEST=ON -D CMAKE_INSTALL_PREFIX=$BASEDIR/release ..

script: 
  - cmake --build . --config $CONFIG --target install
  - export LD_LIBRARY_PATH=$BASEDIR/release/bin:$BASEDIR/release/bin/tests:$BASEDIR/release/lib:$LD_LIBRARY_PATH
  - $BASEDIR/release/bin/printSimdSupport
  - ctest -C $CONFIG || ctest -V -C $CONFIG
  
branches:
  only:
    - master
    
notifications:
  email:
    recipients:
      - mkomm@cern.ch
    on_success: change
    on_failure: always

